[package]
name = "IMAP"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"

transport = { path = "./crates/transport" }

[workspace]
members = [
    "crates/transport"
]
