[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort" 